version: "3"
services:
    frontend:
        container_name: web
        build:
            context: ./Web/client
            dockerfile: Dockerfile
        image: web_cdc:1.0
        ports:
            - "3000:3000"
        volumes:
            - ./Web/client:/usr/src/app
        networks:
            - pgcdc
    backend:
        container_name: web_server
        build:
            context: ./Web/server
            dockerfile: Dockerfile
        image: web_server_cdc:1.0
        ports:
            - "8085:8085"
        volumes:
            - ./Web/server:/usr/src/app
        networks:
            - pgcdc
    database:
        container_name: web_db
        image: mongo:latest
        environment: 
            - MONGO_INITDB_DATABASE=pgcdc_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - ./Web/server/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./Web/server/mongo/mongo-volume:/data/db
        ports:
            - "27017:27017"
        networks:
            - pgcdc

networks:
    pgcdc:
        driver: bridge